version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    #    volumes:
    #      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
  web:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: on-failure
    volumes:
      - .:/server
    ports:
      - "8000:8000"
#volumes:
#  postgres-data: